spring:
  application:
    name: rental-management-service
  datasource:
    url: jdbc:mysql://localhost:3306/rental_info_db
    password: dumith
    username: dumith
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:  port: 8200
car-management-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8100, localhost:8101, localhost:8102